export const UPDATE_EXPANDED_KEYS = 'UPDATE_EXPANDED_KEYS';
export const UPDATE_CHECKED_KEYS = 'UPDATE_CHECKED_KEYS';

export const CHANGE_SEARCH_CONTENT = 'CHANGE_SEARCH_CONTENT';
export const CLEAR_SEARCH_CONTENT = 'CLEAR_SEARCH_CONTENT';

export const FILTER_TREE = 'FILTER_TREE';